export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramChatId: process.env.TELEGRAM_CHAT_ID ?? "",
  autoSignalTelegramBotToken: process.env.AUTO_SIGNAL_TELEGRAM_BOT_TOKEN ?? "",
  autoSignalTelegramChatId: process.env.AUTO_SIGNAL_TELEGRAM_CHAT_ID ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
  openRouterApiKey: process.env.OPENROUTER_API_KEY ?? "",
  alphaVantageApiKey: process.env.ALPHA_VANTAGE_API_KEY ?? "",
  coinGeckoApiKey: process.env.COINGECKO_API_KEY ?? "",
};
