import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Database, RefreshCw, TrendingUp } from 'lucide-react';

function Metric({ label, value, tone = 'text-white' }: { label: string; value: string; tone?: string }) {
  return <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-3"><div className="text-[9px] font-mono font-bold uppercase tracking-wider text-slate-500">{label}</div><div className={`mt-1 text-sm font-black ${tone}`}>{value}</div></div>;
}

export function MacroIndicatorsPanel() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch('/api/macro-indicators', { cache: 'no-store' }); if (!response.ok) throw new Error('Macro feed unavailable'); setData(await response.json()); } catch (err: any) { setError(err.message || 'Macro feed unavailable'); } finally { setLoading(false); } };
  useEffect(() => { load(); const id = window.setInterval(load, 15 * 60 * 1000); return () => window.clearInterval(id); }, []);
  const indicators = data?.indicators || {};
  const formatted = (item: any, suffix = '') => item?.value === null || item?.value === undefined ? 'Unavailable' : `${Number(item.value).toFixed(2)}${suffix}`;
  return <section className="rounded-3xl border border-slate-800 bg-slate-900/95 p-4 sm:p-5" data-testid="macro-indicators-panel"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-cyan-400" /><h2 className="text-sm font-black uppercase tracking-wide text-white">Macro Climate</h2><span className="rounded-full border border-cyan-500/30 bg-cyan-500/10 px-2 py-0.5 text-[9px] font-mono text-cyan-300">FRED PUBLIC</span></div><p className="mt-1 text-[11px] text-slate-500">CPI, labor, policy rate, and the 2Y/10Y yield differential.</p></div><button onClick={load} className="rounded-lg border border-slate-800 bg-slate-950 p-2 text-slate-400 hover:text-white" aria-label="Refresh macro indicators"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} /></button></div>{error && <div className="mt-3 flex items-center gap-2 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-[10px] text-amber-300"><AlertTriangle className="h-3.5 w-3.5" />{error}; retrying on the next refresh.</div>}<div className="mt-4 grid grid-cols-2 lg:grid-cols-5 gap-2"><Metric label="CPI index" value={formatted(indicators.cpi)} tone="text-amber-300" /><Metric label="Unemployment" value={formatted(indicators.unemployment, '%')} tone="text-cyan-300" /><Metric label="Payrolls" value={formatted(indicators.payrolls, 'k')} tone="text-emerald-300" /><Metric label="Fed funds" value={formatted(indicators.policyRate, '%')} tone="text-violet-300" /><Metric label="10Y yield" value={formatted(indicators.tenYear, '%')} /><Metric label="10Y − 2Y" value={indicators.yieldDifferential === null || indicators.yieldDifferential === undefined ? 'Unavailable' : `${Number(indicators.yieldDifferential).toFixed(2)}%`} tone={Number(indicators.yieldDifferential) < 0 ? 'text-rose-300' : 'text-emerald-300'} /></div><div className="mt-3 text-[10px] font-mono text-slate-600">Source: FRED public CSV · Macro data is delayed and should be checked against official releases.</div></section>;
}

export function CryptoMetricsPanel({ symbol = 'BTCUSDT' }: { symbol?: string }) {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(`/api/crypto-metrics?symbol=${encodeURIComponent(symbol)}`, { cache: 'no-store' }); if (!response.ok) throw new Error('Crypto metrics unavailable'); setData(await response.json()); } catch (err: any) { setError(err.message || 'Crypto metrics unavailable'); } finally { setLoading(false); } };
  useEffect(() => { load(); const id = window.setInterval(load, 60 * 1000); return () => window.clearInterval(id); }, [symbol]);
  const derivatives = data?.derivatives || {};
  const onChain = data?.onChain || {};
  const funding = derivatives.fundingRate === null || derivatives.fundingRate === undefined ? 'Unavailable' : `${(Number(derivatives.fundingRate) * 100).toFixed(4)}%`;
  return <section className="rounded-3xl border border-slate-800 bg-slate-900/95 p-4 sm:p-5" data-testid="crypto-metrics-panel"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-emerald-400" /><h2 className="text-sm font-black uppercase tracking-wide text-white">Crypto Market Structure</h2><span className="rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-[9px] font-mono text-emerald-300">{data?.symbol || symbol}</span></div><p className="mt-1 text-[11px] text-slate-500">Funding, open interest, Bitcoin network activity, and upcoming token unlocks.</p></div><button onClick={load} className="rounded-lg border border-slate-800 bg-slate-950 p-2 text-slate-400 hover:text-white" aria-label="Refresh crypto metrics"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} /></button></div>{error && <div className="mt-3 flex items-center gap-2 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-[10px] text-amber-300"><AlertTriangle className="h-3.5 w-3.5" />{error}; partial data may still be available.</div>}<div className="mt-4 grid grid-cols-2 lg:grid-cols-4 gap-2"><Metric label="Funding rate" value={funding} tone={Number(derivatives.fundingRate) > 0.0005 ? 'text-rose-300' : 'text-emerald-300'} /><Metric label="Open interest" value={derivatives.openInterest ? Number(derivatives.openInterest).toLocaleString() : 'Unavailable'} tone="text-violet-300" /><Metric label="Network tx/sec" value={onChain?.network === 'Bitcoin' && onChain.transactionsPerSecond ? Number(onChain.transactionsPerSecond).toFixed(2) : 'BTC only'} /><Metric label="Hash rate" value={onChain?.network === 'Bitcoin' && onChain.hashRate ? `${Number(onChain.hashRate).toFixed(0)} GH/s` : 'BTC only'} /></div><div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/60 p-3"><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-amber-300"><Database className="h-3.5 w-3.5" />Upcoming token unlocks</div>{data?.unlocks?.length ? <div className="mt-2 grid gap-2 sm:grid-cols-2">{data.unlocks.slice(0, 4).map((unlock: any, index: number) => <div key={`${unlock.token}-${index}`} className="flex items-center justify-between gap-2 rounded-lg bg-slate-900 px-2.5 py-2 text-[10px]"><span className="font-bold text-slate-200">{unlock.token}</span><span className="font-mono text-slate-500">{unlock.date ? new Date(unlock.date).toLocaleDateString() : 'Date pending'}</span></div>)}</div> : <p className="mt-2 text-[10px] text-slate-500">No unlock records returned by the public source.</p>}</div><div className="mt-3 text-[10px] font-mono text-slate-600">Sources: Binance Futures · Blockchain.com (Bitcoin network only) · DefiLlama public endpoints. Metrics can be delayed, incomplete, or symbol-specific.</div></section>;
}
